# -*- coding: utf-8 -*-
"""Sentiment_analysis_ML_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vhfgGnS7sW7PAfiIy6fuA8Alx56eyaBH
"""

#!pip install newspaper3k

#import libraries

from textblob import TextBlob
import nltk
from newspaper import Article

url='https://www.verywellmind.com/negative-bias-4589618'
article=Article(url)

#Natural Language Processing
article.download()
article.parse()
nltk.download('punkt')

text=article.summary
print(text)

ob=TextBlob(text)
sentiment=ob.sentiment.polarity
print(sentiment)

if sentiment == 0.0:
  print("The text is neutral")
elif sentiment < 0.0:
  print("The text is negative")
else:
  print("The text is positive")